spin_manifest_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Spin module->component adapter test case"
name = "adapter-test-case"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "adapter-test-case"
source = "target/wasm32-wasi/release/adapter_test_case.wasm"
allowed_http_hosts = ["https://example.com"]
[component.trigger]
route = "/.."
[component.build]
command = "cargo build --target wasm32-wasi --release"
